# 个人电脑本地AI助手 v2.0 配置文件
# 基于Notion技术方案优化升级

server:
  port: 8080
  servlet:
    context-path: /assistant

spring:
  application:
    name: file-ai-assistant-v2
  
  # 数据源配置
  datasource:
    url: jdbc:sqlite:${user.home}/.file-assistant/data/assistant.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLiteDialect
        format_sql: true

# 助手配置
assistant:
  # 存储配置
  storage:
    data-dir: ${user.home}/.file-assistant/data
    index-dir: ${user.home}/.file-assistant/index
    max-index-size: 2GB
    vector-storage: rocksdb
  
  # AI配置
  ai:
    embedding-model: models/all-MiniLM-L6-v2.onnx
    embedding-dimension: 384
    max-concurrent-inference: 2
    model-download-url: https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/resolve/main/onnx/model_quantized.onnx
  
  # 索引配置
  index:
    batch-size: 100
    max-file-size: 50MB
    exclude-patterns:
      - "*.tmp"
      - "*.log"
      - "~$*"
      - "*.cache"
      - "*.lock"
      - ".DS_Store"
      - "Thumbs.db"
  
  # 性能配置
  performance:
    memory-limit: 512MB
    cpu-limit: 50%
    max-concurrent-operations: 4
    cache-size: 1000

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# 日志配置
logging:
  level:
    com.assistant: DEBUG
    org.springframework.web: INFO
    org.apache.tika: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${user.home}/.file-assistant/logs/assistant.log
    max-size: 10MB
    max-history: 30

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
